### ISSUE TITLE
suggest to turn https://www.wikidata.org/wiki/Property:P7715 (World of Flora Online) into an identifier for taxa

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#102]
hey @Daniel-Mietchen - I am trying to add support in GloBI for https://www.wikidata.org/wiki/Property:P7715 (World of Flora Online) for @seltmann and friends. 

However, for some reason, the Datatype is not marked as an identifier for taxa like https://www.wikidata.org/wiki/Property:P815 . 

Can you please help to turn https://www.wikidata.org/wiki/Property:P7715 into an instance of https://www.wikidata.org/wiki/Q42396390 ? 

For some reason, I cannot edit this property.

_Originally posted by @jhpoelen in https://github.com/globalbioticinteractions/nomer/issues/96#issuecomment-1242279200_

**Comment by jhpoelen** [comment]
fyi @Daniel-Mietchen

**Comment by Daniel-Mietchen** [comment]
Should be fixed now:

![image](https://user-images.githubusercontent.com/465923/199299773-d2ae18e6-b70f-4fad-bedf-87f09af7235f.png)

**Comment by jhpoelen** [comment]
@Daniel-Mietchen thanks for updating the WFO wikidata item. Let the linking begin . . . 

![image](https://user-images.githubusercontent.com/1084872/199323914-0e0d0ae6-ff33-47ee-b8a5-b186f054ed2b.png)
