### ISSUE TITLE
Suggest to include authorship past name parsing gn-parse, gbif-parse

### ISSUE THREAD

**Issue by jtmiller28** [globalbioticinteractions/nomer#112]
Ah yes, my bad: 
[my.properties.gz](https://github.com/globalbioticinteractions/nomer/files/9679319/my.properties.gz)

In my ideal world if nomer detects multiple taxonomically valid names for a supplied name it would then query a second tabular input, containing the authorship if provided, to select the intended resolution. If the authorship is not provided, then continue generating multiple possible mappings. 

Example: echo -e "\t×Aegilotriticum requienii\t(Ces., Pass. & Gibelli) P.Fourn." | nomer append gn-parse | nomer append wfo
would provide 
×Aegilotriticum requienii (Ces., Pass. & Gibelli) P.Fourn. SAME_AS × Aegilotriticum requienii SYNONYM_OF WFO:0000841768 ×Aegilotriticum triticoides species ×Aegilotriticum triticoides WFO:0000841768 species http://www.worldfloraonline.org/taxon/wfo-0000841768

Alternatively, providing the authorship of original name path through nomer could allievate workflow for tracing taxonomic names that recieved multiple mappings. Something like: 
echo -e "\t×Aegilotriticum requienii\t(Ces., Pass. & Gibelli) P.Fourn." | nomer append gn-parse | nomer append wfo

×Aegilotriticum requienii (Ces., Pass. & Gibelli) P.Fourn. SAME_AS × Aegilotriticum requienii  **INTENDED_AUTHOR 	
(Ces., Pass. & Gibelli) P.Fourn.** SYNONYM_OF WFO:0000841768 ×Aegilotriticum triticoides species ×Aegilotriticum triticoides 	
* WFO:0000841768 species http://www.worldfloraonline.org/taxon/wfo-0000841768

×Aegilotriticum requienii (Ces., Pass. & Gibelli) P.Fourn. SAME_AS × Aegilotriticum requienii I**NTENDED_AUTHOR (Ces., Pass. & Gibelli) Veldkamp** HAS_ACCEPTED_NAME WFO:0001356228 ×Aegilotriticum requienii species×Aegilotriticum requienii WFO:0001356228 species http://www.worldfloraonline.org/taxon/wfo-0001356228

Hope thats clear, let me know if there's anything too ambiguous in my example

_Originally posted by @jtmiller28 in https://github.com/globalbioticinteractions/nomer/issues/104#issuecomment-1262872493_

**Comment by jhpoelen** [comment]
@jtmiller28 thanks for pointing out that the authorship strings are not being preserved on name parsing using @dimus 's Global Names parser and @mdoering 's GBIF name parser. 

I made a first pass at preserving the authorship strings as formatted by the name parsers. 

using ```my.properties```

```
nomer.append.schema.output.example.taxon.rank.order=[{"column":0,"type":"path.order.id"},{"column": 1,"type":"path.order.name"},{"column": 2,"type":"path.order"}]
nomer.append.schema.output=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"},{"column": 2,"type":"authorship"},{"column":3,"type":"rank"}]
nomer.schema.input=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"},{"column": 2,"type":"authorship"},{"column": 3, "type":"rank"}]
```

I was able to produce:

```
$ echo -e "\tHomo sapiens Linneaus 1758" | nomer append gbif-parse --include-header --properties my.properties 
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [gbif-parse]
providedExternalId	providedName	relationName	resolvedExternalId	resolvedName	resolvedAuthorship	resolvedRank
	Homo sapiens Linneaus 1758	SAME_AS		Homo sapiens	Linneaus, 1758	
```

and 

```
$ echo -e "\tHomo sapiens Linneaus 1758" | nomer append gn-parse --include-header --properties my.properties 
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [gn-parse]
providedExternalId	providedName	relationName	resolvedExternalId	resolvedName	resolvedAuthorship	resolvedRank
	Homo sapiens Linneaus 1758	SAME_AS		Homo sapiens	Linneaus 1758	
```

note that GBIF parser adds a comma between name and year, whereas GN parser leaves does not insert the comma. 

Hoping to include this functionality in upcoming nomer release.

**Comment by jtmiller28** [comment]
Thanks jorrit! I'll add this to my workflow and provide feedback once name resolution occurs.

**Comment by jhpoelen** [comment]
https://github.com/globalbioticinteractions/nomer/releases/tag/0.3.1 is now available with fix for this issue. @jtmiller28 please review.

**Comment by dimus** [comment]
Note that authors are sometimes abbreviated, omitted, or ordered in a different way. Because of that direct comparison of authors does not work all the time. So gnresolver uses this algorithm for matching https://github.com/gnames/gnames/blob/master/ent/score/auth.go

**Comment by jhpoelen** [comment]
And with WFO

```
echo -e "\tHelianthemum scoparium\tNutt. ex Torr. & A.Gray" |  nomer append wfo --include-header 
```


| providedExternalId | providedName | providedAuthorship | relationName | resolvedExternalId | resolvedName | resolvedAuthorship | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedPathAuthorships | resolvedExternalUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | Helianthemum scoparium | Nutt. ex Torr. & A.Gray | HAS_ACCEPTED_NAME | WFO:0001295598 | Helianthemum scoparium | Nutt. ex Torr. & A.Gray | species |  | Angiosperms \| Malvales \| Cistaceae \| Helianthemum \| Helianthemum scoparium | WFO:9949999999 \| WFO:9000000312 \| WFO:7000000136 \| WFO:4000017201 \| WFO:0001295598 | phylum \| order \| family \| genus \| species |  | http://www.worldfloraonline.org/taxon/wfo-0001295598 |
