### ISSUE TITLE
How to use nomer behind a proxy?

### ISSUE THREAD

**Issue by zedomel** [globalbioticinteractions/nomer#121]
Hi @jhpoelen 

I'm using a machine which is behind a HTTP(S) proxy. I tried to set up java proxy settings but it did not work:

```bash
export JAVA_OPTS="-Dhttp.proxyHost=proxyHost -Dhttp.proxyPort=proxyPort -Dhttps.proxyHost=proxyHost -Dhttps.proxyPort=proxyPort"
```

where `proxyHost` and `proxyPort` are replaced by the proxy's host and port respectively. 

Any idea how make it to work?

thanks
josé

**Comment by jhpoelen** [comment]
@zedomel thanks for asking. I'll hope to have a look at this sooner rather than later. 

In an ideal world, how would you want to configure your host/port proxy?

**Comment by jhpoelen** [comment]
@zedomel just upgraded Nomer to globi lib v0.24.4 with http proxy support. Please let me know if the current dev version of Nomer works behind a proxy using the System properties you used earlier.

**Comment by jhpoelen** [comment]
If it does . . . do you mind translating https://www.globalbioticinteractions.org/pt/ ? Gotta make sure these interactions are a little easier to find in [São Paulo](https://en.wikipedia.org/wiki/S%C3%A3o_Paulo) :wink:

**Comment by jhpoelen** [comment]
closing stale issue, @zedomel please comment or re-open is issues remain.
