### ISSUE TITLE
add support for aligning with Mammal Diversity Database https://mammaldiversity.org 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#141]
@n8upham add support for aligning with Mammal Diversity Database https://mammaldiversity.org 

See also https://github.com/globalbioticinteractions/nomer/issues/108

**Comment by jhpoelen** [comment]
Preliminary result after implementing a first pass at MDD support resulted in 

Some bat names in https://batnames.org that did not appear in MDD. First 10 include:

```
$ nomer ls batnames  | cut -f1,2 | nomer append mdd | grep NONE | cut -f2 | sort | uniq | head
Afronycteris nana
Baeodon alleni
Baeodon gracilis
Carollia brevicauda
Dobsonia magna
Eptesicus alienus
Eptesicus cadenai
Eptesicus colombiae
Eptesicus diaphanopterus
Eptesicus guadeloupensis
```

The first name has screenshot in batnames - 

![image](https://user-images.githubusercontent.com/1084872/214165151-550a2c74-b873-48d6-932f-9ffdae11cfc5.png)

But no hits in MDD.

However, note that in MDD genus "Afronycteris" does include specific epithet "nanus" , suggesting that batnames and MDD differ in genderized suffixes. (see related https://github.com/globalbioticinteractions/nomer/issues/143 , https://www.mammaldiversity.org/explore.html#genus=Afronycteris&species=nanus&id=1005700 and attached MDD screenshots).

![Screenshot from 2023-01-23 16-35-06](https://user-images.githubusercontent.com/1084872/214165585-2f969555-84fe-4211-95d0-22262253343b.png)

![image](https://user-images.githubusercontent.com/1084872/214165767-c43d62dd-872a-40d9-9072-d148ab00dd63.png)

**Comment by n8upham** [comment]
Very cool @jhpoelen !  Which authority does MDD end up being aligned to here?  For the example would you be able to align to NCBI, for example, and if so are any synonyms used in the name matching?  Thanks much

**Comment by jhpoelen** [comment]
@n8upham thanks for taking the time to ask a question about this recently introduced MDD support in Nomer v0.4.9 .

In https://github.com/jhpoelen/Mormoopidae/ , [Nancy's list](https://github.com/jhpoelen/Mormoopidae/blob/main/Mormoopidae.txt) is being aligned with various authorities, including MDD v1.10  . You can find the configuration for this specific alignment workflow at:
https://raw.githubusercontent.com/jhpoelen/Mormoopidae/main/README.md

However, in https://github.com/jhpoelen/compare-mdd-with-other-catalogs all of MDD is aligned with various other Nomer authorities.You can find the configuration of this alignment at:
https://raw.githubusercontent.com/jhpoelen/compare-mdd-with-other-catalogs/main/README.md

As far as synonyms go: currently authorities included in Nomer map from synonyms to accepted names, not the other way around. So, that means that if NCBI recognizes one of MDDs names as a synonym, it'll resolve to the accepted name. 

Hope this answers your questions. If not or if you have any suggestions or see any inconsistencies, please do holler.
