### ISSUE TITLE
Matching EOL taxon ids from interactions.tsv returns None

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#15]
Hi @jhpoelen 

I am facing a problem when using nomer to match taxon ids from GloBi's TSV dump file interactions.tsv. I tried matching the first 10 source ids and target ids , which all appear to be EOL or EOL_V2 ids, and nomer returns NONE for all of them (using globi-enrich). For instance :

```bash
echo -e "EOL:12001247\t" | nomer append globi-enrich
using matcher [globi-enrich]
lazy init of taxonomy index [GulfBaseService] started...
index directory at [/tmp/taxon1586532735216] created.
lazy init of taxonomy index [GulfBaseService] done.
EOL:12001247		NONE	EOL:12001247	http://eol.org/pages/12001247
```

Would there be an issue related to EOL ids ?

Thank you for your help.

**Comment by jhpoelen** [comment]
Hi @nleguillarme - 

If you are trying to match the EOL ids from the GloBI interactions.tsv, I suggest to use:

```
$ echo -e "EOL:12001247\t" | nomer append
using default matcher [globi-taxon-cache]
EOL:12001247		SAME_AS	EOL:12001247	Leptoconchus massini	species		Animalia | Mollusca | Gastropoda | Neogastropoda | Muricoidea | Muricidae | Leptoconchus | Leptoconchus massiniEOL:1 | EOL:2195 | EOL:2366 | EOL:2447 | EOL:4846903 | EOL:2461 | EOL:4824764 | EOL:12001247	kingdom | phylum | class | order | superfamily | family | genus | species	http://eol.org/pages/12001247	
```
This method downloads the GloBI Taxon Cache (see version via ```nomer properties```) to enable fast matching against ids.  

The matchers ```globi-enrich``` is using web apis to resolve terms. Please also note that support for resolving via the EOL web api was removed in preparation for https://github.com/globalbioticinteractions/nomer/issues/11 . Unfortunately, I have not yet have the opportunity to work on providing offline access to the EOL dynamic hierarchy. ; (

**Comment by jhpoelen** [comment]
Note that ```nomer append``` is shorthand for ```nomer append globi-taxon-cache``` :

```
$ echo -e "EOL:12001247\t" | nomer append globi-taxon-cache
EOL:12001247		SAME_AS	EOL:12001247	Leptoconchus massini	species		Animalia | Mollusca | Gastropoda | Neogastropoda | Muricoidea | Muricidae | Leptoconchus | Leptoconchus massiniEOL:1 | EOL:2195 | EOL:2366 | EOL:2447 | EOL:4846903 | EOL:2461 | EOL:4824764 | EOL:12001247	kingdom | phylum | class | order | superfamily | family | genus | species	http://eol.org/pages/12001247	
```

**Comment by nleguillarme** [comment]
> Please also note that support for resolving via the EOL web api was removed in preparation for #11.

Great ! That's the information I was looking for. Thank you.

I generally use a combination of globi-taxon-cache and globi-enrich to match my IDs. Unfortunately, the cache does not always load when using nomer in docker. But I will try to investigate this point further.

**Comment by nleguillarme** [comment]
Using globi-taxon-cache, I still have a lot of NONE results for taxa in the interactions.tsv file. For instance,

```bash
echo -e "EOL:200339\t" | nomer append globi-taxon-cache
using matcher [globi-taxon-cache]
EOL:200339		NONE	EOL:200339
```

```bash
echo -e echo -e "EOL:200324\t" | nomer append globi-taxon-cache
using matcher [globi-taxon-cache]
EOL:200324		NONE	EOL:200324
```

And so on...

**Comment by jhpoelen** [comment]
Thanks for sharing your explicit examples. Before I dig into the details, can you confirm that the EOL ids you mention are extracted from the source/targetTaxonPathIds column? If not, could you please share the line in interactions.tsv that you extracted this from.

**Comment by nleguillarme** [comment]
I just tested my pipeline on the first 9 entries from interactions.tsv

No problem with the source ids (column sourceTaxonId), but only EOL_V2 ids match when processing column targetTaxonId (all EOL ids are mapped to NONE).


targetTaxonId
--
EOL:200339
EOL:200324
EOL:200337
EOL:200336
EOL:200333
EOL_V2:200352
EOL_V2:200354
EOL:200332
EOL_V2:200365

**Comment by jhpoelen** [comment]
Thanks for your examples!

I ran:
```
$ cat interactions.tsv.gz | gunzip | grep "200339"
```

And its results included:

EOL:12001247	EOL:12001247 | GBIF:5857279 | IRMNG:11733708 | NCBI:494640 | OTT:133330 | WD:Q13393587 | WORMS:579844	Leptoconchus massini	species	Animalia | Mollusca | Gastropoda | Neogastropoda | Muricoidea | Muricidae | Leptoconchus | Leptoconchus massini	EOL:1 | EOL:2195 | EOL:2366 | EOL:2447 | EOL:4846903 | EOL:2461 | EOL:4824764 | EOL:12001247	kingdom | phylum | class | order | superfamily | family | genus | species	Leptoconchus massini	EOL:12001247	Leptoconchus	EOL:4824764	Muricidae	EOL:2461	Neogastropoda	EOL:2447	Gastropoda	EOL:2366	Mollusca	EOL:2195	Animalia	EOL:1														parasiteOf	http://purl.obolibrary.org/obo/RO_0002444	**EOL_V2:200339**	EOL_V2:200339 | GBIF:2260629 | IRMNG:11164834 | ITIS:53123 | OTT:298818 | WD:Q3940689	Fungia repanda	species	Animalia | Cnidaria | Anthozoa | Scleractinia | Fungiidae | Fungia | Fungia repanda	EOL:1 | EOL:1745 | EOL:1746 | EOL:1799 | EOL_V2:6641 | EOL_V2:23276 | EOL_V2:200339	kingdom | phylum | class | order | family | genus | species	Fungia repanda	EOL_V2:200339	Fungia	EOL_V2:23276	Fungiidae	EOL_V2:6641	Scleractinia	EOL:1799	Anthozoa	EOL:1746	Cnidaria	EOL:1745	Animalia	EOL:1			https://en.wiktionary.org/wiki/support	Gittenberger, A., Gittenberger, E. (2011). Cryptic, adaptive radiation of endoparasitic snails: sibling species of Leptoconchus (Gastropoda: Coralliophilidae) in corals. Org Divers Evol, 11(1), 21–41. doi:10.1007/s13127-011-0039-1	10.1007/s13127-011-0039-1		Jorrit H. Poelen. 2014. Species associations manually extracted from literature.	FloraVincent/template-dataset	https://github.com/FloraVincent/template-dataset/archive/949abcbe08011c1d9fa53327ad5dc1d6be728a95.zip		2019-03-30T23:08:44.205Z

and 

```
$ echo -e "EOL_V2:200339\t" | nomer append globi-taxon-cache
using matcher [globi-taxon-cache]
EOL_V2:200339		SAME_AS	EOL_V2:200339	Fungia repanda	species	mushroom coral @en |	Animalia | Cnidaria | Anthozoa | Scleractinia | Fungiidae | Fungia | Fungia repanda	EOL:1 | EOL:1745 | EOL:1746 | EOL:1799 | EOL_V2:6641 | EOL_V2:23276 | EOL_V2:200339	kingdom | phylum | class | order | family | genus | species	http://eol.org/pages/200339	
```

However, as you noted,

```
$ echo -e "EOL:200339\t" | nomer append globi-taxon-cache
using matcher [globi-taxon-cache]
EOL:200339		NONE		EOL:200339							
```

And, when scanning interactions.tsv.gz for the id and related terms:

```
$ cat interactions.tsv.gz | gunzip | grep "200339" | wc -l
59
$ cat interactions.tsv.gz | gunzip | grep "EOL_V2:200339" | wc -l
10
$ cat interactions.tsv.gz | gunzip | grep "EOL:200339" | wc -l
0
```

This supports the idea that ```EOL:200339``` does not appear in interactions.tsv.gz (e.g., no lines matching ```EOL:200339```, but 10 lines matching ```EOL_V2:200339```) . So, I am curious - where did you get the id from?

**Comment by nleguillarme** [comment]
Damn ! It seems that I am working with an obsolete version of interactions.tsv from mid-2019.
I thought I downloaded the latest version. I'm sorry I wasted your time.

**Comment by jhpoelen** [comment]
No worries! This actually highlighted something that I've been wanting to do for a while - pushing released versions of interactions.tsv.gz to Zenodo or some other platforms. I imagine it is hard to reference interactions.tsv.gz that keep changing. See https://github.com/globalbioticinteractions/globalbioticinteractions/issues/475 .
