### ISSUE TITLE
adding an equivalent of alignedAuthority for parsed name

### ISSUE THREAD

**Issue by whitfarnum** [globalbioticinteractions/nomer#160]
I am in a situation where I am verifying names in a historical insect collection. It is curated to a 19th century standard. We want to verify the names in the collection were once correct. As I am aligning names I can get the author for the current name but of the name I provided to the search. For my particular use case I am using GBIF since they have an authoritative Carabidae dataset and they have the authors in the results pages like
https://www.gbif.org/species/1035266

Thanks for a great tool. It is making my curation and name validation go much faster.

**Comment by jhpoelen** [comment]
@whitfarnum thanks for your message. Can you please add a specific example of what the tool does today, and how you'd like it to behave instead. Some specific examples help me to better understand what you have in mind. Thanks for being patient.

**Comment by whitfarnum** [comment]
@jhpoelen 
providedName: Clivina elongata
parsedName: Clivina elongata
alignedName: Dyschirius politus politus
alignedAuthority: (Dejean, 1825)
alignedExternalId: http://www.gbif.org/species/8915572

In the gbif page I can learn that the authority for Clivina elongata is Ahrens, 1830
I would call this parsedAuthority: Ahrens, 1830. Nomer currently provides no information about the authorship of the providedName/parsedName.

I may also be helpful if provided names are synonyms and you want to be able to trace it better.

**Comment by jhpoelen** [comment]
Ah, thanks for clarifying! 

currently: 

providedName: Clivina elongata
parsedName: Clivina elongata
alignedName: Dyschirius politus politus
alignedAuthority: (Dejean, 1825)
alignedExternalId: http://www.gbif.org/species/8915572

desired:

providedName: Clivina elongata
parsedName: Clivina elongata
parsedNameAuthority: Ahrens, 1830
alignedName: Dyschirius politus politus
alignedAuthority: (Dejean, 1825)
alignedExternalId: http://www.gbif.org/species/8915572

In my mind, parsing and aligning are different processes:

1. parsing takes a name string and chops it according to nomenclature rules.
2. aligning takes some name catalog and associates a name with the provided name via some sort of relation

So, in your example, I say something like:


providedName: Clivina elongata
parsedName: Clivina elongata
alignedRelation: same_as (or equivalent_to)
alignedName: Clivina elongata
alignedAuthority: Ahrens, 1830

*and*


providedName: Clivina elongata
parsedName: Clivina elongata
alignedRelation: has_accepted_name
alignedName: Dyschirius politus politus
alignedAuthority: (Dejean, 1825)

Curious to hear your thoughts on separating out the different kind of relations (e.g., same_as, has_accepted_name)

**Comment by jhpoelen** [comment]
@whitfarnum just curious - do you happen to have access to programmers at your institution? Would be great to get folks to get more eyes on these tools are requirements . . .

**Comment by whitfarnum** [comment]
@jhpoelen 
contact Crystal Maier (cmaier@g.harvard.edu) and she will put you in touch with our programmers.

**Comment by jhpoelen** [comment]
@whitfarnum please feel free to bring it up when there's an opportunity, unless you think it is best to do the email thing. It was just an idea to make our party a little bigger ; )

**Comment by whitfarnum** [comment]
@jhpoelen this would probably best be done via email. Drop Crystal a line.

**Comment by whitfarnum** [comment]
@jhpoelen 
I see the the parsing and alignening as the act of assigning an input string to some number of matching strings and then assigning those matching strings to the current accepted string.
Example
providedName: Carabus bicolor 
parsed name: Carabus bicolor 
parse authority: McKenna 1920
alignedRelation: same_as (or equivalent_to)
alignedName: Clivina elongata
alignedAuthority: Ahrens, 1830

where this is all one line in the data set.

I use nomer as a method to match taxa to current names and then update those names in an inventory. In cases where homonyms exists it is useful to know the authors attached to the parsedAuthority not just the alignedAuthority. I want data attached to my input name. If cases arise where the provided names maps to multiple names in the case of homonyms that is fine. I need to know the authors associated with the names so I can match them to the author listed on the determination label or unit tray label.

**Comment by jhpoelen** [comment]
@whitfarnum let me if you have additional notes / questions, otherwise, I'll consider this issue closed.
