### ISSUE TITLE
Subgenus added to Discover Life

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#161]
Hi @jhpoelen the new update to nomer with Discover Life looks great and it is now also published as a Zenodo archive (see https://zenodo.org/record/8291887).

I would like to see if we can add subgeneric names of bees to nomer. These are found on the species pages if the resolvedExternalId is followed. For bees, subgeneric names are important because often bees are identified to subgenus but not below. For example:

Agapostemon texanus has the id of https://www.discoverlife.org/20/q?search=Agapostemon+texanus

On the webpage the subgenus is listed as:
 
`<br><small>Subgenus: <a href="[/mp/20p?see=Agapostemon&name=Agapostemon&flags=subgenus:](https://www.discoverlife.org/mp/20p?see=Agapostemon&name=Agapostemon&flags=subgenus:)"><i>Agapostemon</i></a></small>`

This could be included as part of the resolvedName, or resolvedPath

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing your example of a bee subspecies. See also https://github.com/globalbioticinteractions/nomer/issues/134 .

**Comment by jhpoelen** [comment]
In order to work with DiscoverLife species pages, I packaged the pages (all 20k of them) in a versioned Preston archive at https://github.com/Big-Bee-Network/discoverlife-bee-archive . 

In the readme, I included an example of how to query for Subgenus names, and list the top 10 most frequently appearing ones - 

~~~
   5600 None
    765 Uncertain
    448 Perdita
    403 Dialictus
    259 Hemihalictus
    209 Eutricharaea
    179 Ctenonomia
    161 Homalictus
    152 Anthidium
    151 Lasioglossum
~~~

This is a first step towards integrating the subgenus information from the DiscoverLife bee species pages into a resource that Nomer can use. All this took about 2-3 hours of hacking, and this shows the expense of publishing data in ways that cannot be easily reused, especially given that the time of researchers, data engineers is a limited and non-sustainable resource.

**Comment by jhpoelen** [comment]
As discussed with @seltmann , proposed to switch the discover life supports from using the scraped data [1] to the published data [2].

## References

[1] Seltmann, K., & Poelen, J. (2024). Tab and comma delimited versions of Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila) (56.1) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10019874

[2] Poelen, J., & Seltmann, K. (2024). RDS and Tab-Separated-Values Formats of Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila) as derived from Dorey et al. 2023 hash://sha256/56e0b3d68f221ee79d61f6da7bfdfad927d63ab86700b856d0a42a133841779c hash://md5/3bb89ee91f9b9a834e8b2725c3729cf5 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.10463762

**Comment by jhpoelen** [comment]
please see attached a working copy of

```nomer ls discoverlife```

based on newly introduced support for discoverlife xml format. 

[discoverlife.tsv.gz](https://github.com/globalbioticinteractions/nomer/files/14962990/discoverlife.tsv.gz)

**Comment by jhpoelen** [comment]
With upcoming Nomer release, the subgenus is included in the taxonomic path as requested.

For instance, when running

```
echo -e "\tAgapostemon texanus"\
 | nomer append --include-header discoverlife\
 | mlr --itsvlite --omd cat
```

The subgenus "Agapostemon" is reported for the species _Agapostemon texanus_ .

| providedExternalId | providedName | relationName | resolvedExternalId | resolvedName | resolvedAuthorship | resolvedRank | resolvedCommonNames | resolvedPath | resolvedPathIds | resolvedPathNames | resolvedPathAuthorships | resolvedExternalUrl |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  | Agapostemon texanus | HAS_ACCEPTED_NAME | https://www.discoverlife.org/mp/20q?guide=Apoidea_species&search=Agapostemon+texanus | Agapostemon texanus | Cresson, 1872 | species |  | Animalia \| Arthropoda \| Insecta \| Hymenoptera \| Halictidae \| Halictinae \| Halictini \| Caenohalictina \| Agapostemon \| Agapostemon \| Agapostemon texanus |  | kingdom \| phylum \| class \| order \| family \| subfamily \| tribe \| subtribe \| genus \| subgenus \| species |  | https://www.discoverlife.org/mp/20q?guide=Apoidea_species&search=Agapostemon+texanus |
