### ISSUE TITLE
What's the default matcher?

### ISSUE THREAD

**Issue by mielliott** [globalbioticinteractions/nomer#173]
Hey @jhpoelen, thanks for creating this lovely tool and potentially saving me a bunch of work and headaches! Just wondering what the default matcher is? I notice `nomer append` with no specified matcher find IDs from EOL, GBIF, ITIS, WORMS, IRMING, Plazi, and on and on (see below). Does the default matcher combine all the other matchers? (hopefully this question makes sense, I have <1 hour experience with nomer)

My use case is: for any given taxon, I'm trying to find all the different ways its been classified, ever, by everyone, everywhere, every year

```bash
$ echo -e "\tActinopterygii" | nomer append --with-header | mlr --tsvlite cat
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using default matcher [globi-taxon-cache]
providedExternalId      providedName    relationName    resolvedExternalId      resolvedName    resolvedAuthorship      resolvedRank    resolvedCommonNames     resolvedPath    resolvedPathIds resolvedPathNamesresolvedPathAuthorships resolvedExternalUrl
        Actinopterygii  SAME_AS EOL:1905        Actinopterygii          class           Life | Cellular Organisms | Eukaryota | Opisthokonta | Metazoa | Bilateria | Deuterostomia | Chordata | Vertebrata | Gnathostomata | Osteichthyes | Actinopterygii       EOL:2913056 | EOL:6061725 | EOL:2908256 | EOL:2910700 | EOL:1 | EOL:3014411 | EOL:8814528 | EOL:694 | EOL:2774383 | EOL:46557929 | EOL:2775704 | EOL:1905       null | null | domain | null | kingdom | null | null | phylum | subphylum | null | null | class           http://eol.org/pages/1905
        Actinopterygii  SAME_AS GBIF:204        Actinopterygii          class           Animalia | Chordata | Actinopterygii    GBIF:1 | GBIF:44 | GBIF:204     kingdom | phylum | class                https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=7898
        Actinopterygii  SAME_AS IRMNG:1530      Actinopterygii          class           Animalia | Chordata | Actinopterygii    IRMNG:11 | IRMNG:148 | IRMNG:1530       kingdom | phylum | class                https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=7898
        Actinopterygii  SAME_AS ITIS:161061     Actinopterygii          superclass              Animalia | Bilateria | Deuterostomia | Chordata | Vertebrata | Gnathostomata | Actinopterygii   ITIS:202423 | ITIS:914154 | ITIS:914156 | ITIS:158852 | ITIS:331030 | ITIS:914179 | ITIS:161061  kingdom | subkingdom | infrakingdom | phylum | subphylum | infraphylum | superclass             https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=7898
        Actinopterygii  SAME_AS WORMS:10194     Actinopterygii          class           Biota | Animalia | Chordata | Vertebrata | Gnathostomata | Pisces | Actinopterygii      WORMS:1 | WORMS:2 | WORMS:1821 | WORMS:146419 | WORMS:1828 | WORMS:11676 | WORMS:10194   null | kingdom | phylum | subphylum | superclass | superclass | class           https://www.marinespecies.org/aphia.php?p=taxdetails&id=10194
        Actinopterygii  SAME_AS doi:10.5281/zenodo.3922354      doi:10.5281/zenodo.3922354                              doi:10.5281/zenodo.3922354                              https://doi.org/10.5281/zenodo.3922354
        Actinopterygii  SAME_AS EOL_V2:4656086  Pisces          superclass      Fish @en | Poissons @fr | Pesci @it | vissen @nl | Peisses @oc | Рыбы @ru | Риби @uk |  Biota | Animalia | Chordata | Vertebrata | Gnathostomata | Pisces        EOL:41445 | EOL:1 | EOL:694 | EOL:2774383 | EOL:12094272 | EOL_V2:4656086       kingdom | kingdom | phylum | subphylum | superclass | superclass                https://doi.org/10.5281/zenodo.1495266#4656086
        Actinopterygii  SAME_AS http://taxon-concept.plazi.org/id/Animalia/Pisces_Linnaeus_1758 Pisces                          Animalia | Chordata | Pisces            kingdom | phylum | class                http://taxon-concept.plazi.org/id/Animalia/Pisces_Linnaeus_1758
        Actinopterygii  SAME_AS http://treatment.plazi.org/id/21430E9C6188A40A2DCF177F0B48AFD2  http://treatment.plazi.org/id/21430E9C6188A40A2DCF177F0B48AFD2                          http://treatment.plazi.org/id/21430E9C6188A40A2DCF177F0B48AFD2                           http://treatment.plazi.org/id/21430E9C6188A40A2DCF177F0B48AFD2
        Actinopterygii  SAME_AS WD:Q127282      Actinopterygii          class           | Actinopterygii        WD:Q27207 | WD:Q127282  null | class            https://www.wikidata.org/wiki/Q127282
```

**Comment by jhpoelen** [comment]
@mielliott Thanks for your question. The default matcher is GloBI (and it probably shouldn't be . . . ) . GloBI matchers only takes taxa encountered in GloBI along with associated taxonomic ids. In other words, GloBI matcher is really only useful when working with GloBI data.

**Comment by mielliott** [comment]
Ok, thanks! Maybe I should choose a few matchers and concat their results. Do the non-globi matchers do any automatic preprocessing akin to `globi-correct` and `globi-scrub`? Should I expect the outputs of different matchers (specifically the taxonomy-related ones) to be compatible in terms of format and output types? Do the other matchers use preston underneath to record data provenance?

Or if you have any advice on applying nomer to the use case of finding lots of synonyms and classifications of a given term, that'd be very helpful as well. I expect their are a lot of traps and caveats that are only obvious to folks more familiar with the data.

Thanks for your time 🙏 I realize I could just try a lot of this by myself, but I've found it can take a while to run these things before caches are built.

**Comment by jhpoelen** [comment]
> Thanks for your time 🙏 I realize I could just try a lot of this by myself, but I've found it can take a while to run these things before caches are built.

You can use pre-built caches. For example, see https://github.com/globalbioticinteractions/globinizer/blob/master/align-names.sh which is built into the https://github.com/globalbioticinteractions/name-alignment-template . You might be surprised that GitHub will run the name alignment workflows for you from scratch in minutes.

**Comment by jhpoelen** [comment]
@mielliott Curious to hear how the Nomer matching worked out for you, or if there's some other method you ended up using.

About the default matcher - would you say it may be more intuitive to *not* have a default matcher, and just complain when none is provided?

**Comment by mielliott** [comment]
> @mielliott Curious to hear how the Nomer matching worked out for you, or if there's some other method you ended up using.

It worked great! I used your name alignment template. For my 2095 names, it found 1203 synonyms and 18,131 unique classification paths, using all the matchers except the fungi ones.

I did have an issue where it would only use one of the input datasets I provided, so I ended up having to combine them into one file, which is fine. If interested, see https://github.com/mielliott/idigbio-sample-alignment/actions/runs/8238275870 and https://github.com/mielliott/idigbio-sample-alignment/tree/c909eb7aa5d17e7a64294ee43ef23dc519107667

> About the default matcher - would you say it may be more intuitive to not have a default matcher, and just complain when none is provided?

I like the idea of requiring the matcher to be specified

**Comment by mielliott** [comment]
> I like the idea of requiring the matcher to be specified

Although I did eventually notice that nomer does say what the default matcher is... I suppose that's fine too

```
$ echo -e "\tBombus" | nomer append
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using default matcher [globi-taxon-cache]
...
```

**Comment by jhpoelen** [comment]
@mielliott following your recommendation, nomer matches should now be stated explicitly. 

e.g.,

```nomer append``` no longer implies ```nomer append globi```, but prints the usage instead:

```
Missing required parameter: '<matchers>'
Usage: nomer append [--with-header] [-o=<outputFormat>]
                    [-p=<propertiesResource>] <matchers>...
Append term match to row using id and name columns specified in input schema.
Multiple matches result in multiple rows.
      <matchers>...   [matcher]
  -o, --output-format=<outputFormat>
                      tsv, json
  -p, --properties=<propertiesResource>
                      Path to properties file to override defaults.
      --with-header, --include-header
                      include table header
```

thanks for your suggestion!

Do you think can can close this issue?

**Comment by mielliott** [comment]
I love it! Thanks again, closing
