### ISSUE TITLE
WoRMS: accepted taxon id urn:lsid:marinespecies.org:taxname:614620  referenced as accepted name usage id in urn:lsid:marinespecies.org:taxname:110231, but urn:lsid:marinespecies.org:taxname:614620 is not provided.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#179]
in line 10338 of June 2024 version of WoRMS, 

```
preston cat\
 --remote https://linker.bio\
 `line:zip:hash://sha256/ca4baa1a90f4ce80d27ec7d1525f54a75fa679d76a66ed6143b17031287dea09!/taxon.txt!/L1,L10338`
```

yielded:

```
taxonID                  urn:lsid:marinespecies.org:taxname:110231
scientificNameID         urn:lsid:marinespecies.org:taxname:110231
acceptedNameUsageID      urn:lsid:marinespecies.org:taxname:614620
parentNameUsageID        urn:lsid:marinespecies.org:taxname:109553
namePublishedInID        
scientificName           Protoperidinium mariaelebouriae
acceptedNameUsage        Protoperidinium marielebouriae
parentNameUsage          Protoperidinium
namePublishedIn          
namePublishedInYear      
kingdom                  Chromista
phylum                   Myzozoa
class                    Dinophyceae
order                    Peridiniales
family                   Protoperidiniaceae
genus                    Protoperidinium
subgenus                 
specificEpithet          mariaelebouriae
infraspecificEpithet     
taxonRank                Species
scientificNameAuthorship (Paulsen) Balech
nomenclaturalCode        ICN
taxonomicStatus          unaccepted
nomenclaturalStatus      
modified                 2012-04-23
bibliographicCitation    WoRMS (2024). Protoperidinium mariaelebouriae (Paulsen) Balech. Accessed at: https://marinespecies.org/aphia.php?p=taxdetails&id=110231
references               https://www.marinespecies.org/aphia.php?p=taxdetails&id=110231
license                  
rightsHolder             
datasetName              
institutionCode          
datasetID                
```

However, an associated html landing page https://www.marinespecies.org/aphia.php?p=taxdetails&id=614620 exists. 

![Screenshot from 2024-06-18 12-01-03](https://github.com/globalbioticinteractions/nomer/assets/1084872/56ab09e3-9329-486d-b063-8f735147459c)

![image](https://github.com/globalbioticinteractions/nomer/assets/1084872/4392a09f-97b1-448a-9e19-26c064669e83)

**Comment by jhpoelen** [comment]
@mdoering @timrobertson100 any idea why this WoRMS  urn:lsid:marinespecies.org:taxname:614620 taxon is referenced, but not defined in:

> WoRMS Editorial Board. (2024). World Register of Marine Species (S. Ahyong, C. Boyko, N. Bailly, J. Bernot, R. Bieler, S. Brandão, M. Daly, S. De Grave, S. Gofas, F. Hernandez, L. Hughes, T. A. Neubauer, & G. Paulay, Eds.; Version 2024-06-01). WoRMS Editorial Board, Belgium. https://doi.org/10.14284/170

**Comment by mdoering** [comment]
No, best to ask someone from WoRMS like @bart-v

**Comment by jhpoelen** [comment]
@mdoering thanks for responding!

@bart-v any ideas why 

WoRMS: accepted taxon id urn:lsid:marinespecies.org:taxname:614620 referenced as accepted name usage id in urn:lsid:marinespecies.org:taxname:110231, but urn:lsid:marinespecies.org:taxname:614620 is not provided.

?

**Comment by jhpoelen** [comment]
This is in WoRMS versions as documented in

Poelen, J. H. (2024). World Register of Marine Species (WoRMS) Repackaged hash://sha256/4e969a1c8243b523b093d3a05fd5f7683479c2919e7d83e8b1383c5e5ef1d4e5 hash://md5/fb7559ce707d11f96a878d8a8a79a661 (0.1) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.12112610

**Comment by bart-v** [comment]
Yes, this is normal.
We are not allowed to redistribute AlgaeBase data

**Comment by jhpoelen** [comment]
@bart-v Thanks for confirming!
