### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by zygoballus** [globalbioticinteractions/nomer#191]
Some of the examples in the README no longer work. For example:
`$ echo -e "NCBI:9606\t" | nomer append > matches.tsv`
`$ echo -e "\tHomo sapiens" | nomer append > matches.tsv`
... since `nomer append` now requires specifying a matcher.

Also it would be nice to update the matchers list in the README.

Also, the 4th paragraph of the README mentions the `globi-cache` matcher (which doesn't seem to exist anymore) and makes it sound like it's the only matcher that does offline matching, when there are actually many.

Finally, you should put some kind of warning in the 4th paragraph that some of the offline matchers may take an extremely long time to download (and take up hundreds of megabytes of space).

**Comment by jhpoelen** [comment]
@zygoballus thanks for taking the time to review the README. This tells me that you care. 

I hope to respond to your notes and make updates to README as soon as I can. Please do note that this is a small project with big dreams, so any help (e.g., pull requests) is welcome.

**Comment by jhpoelen** [comment]
@zygoballus I took some time to update the README as you suggested. 

Please review and let me know if have additional comments.

**Comment by jhpoelen** [comment]
@zygoballus thanks again for having a look. I fixed the typo you pointed out. Please do holler if you have more suggestions you.
