### ISSUE TITLE
Get taxon ID in target taxonomy

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#22]
Hi @jhpoelen.

My use case requires converting a taxon ID from a source taxonomy (let's say EOL) to a specific target taxonomy (e.g. GBIF).

I don't think this is possible using nomer, right ? I guess the closer I can get is using globi-globalnames with the taxon name.

However, I know that this kind of mapping is done in GloBi, so I was wondering how you did that, and if it could be reused in nomer ?

Best regards.

**Comment by nleguillarme** [comment]
@jhpoelen thanks for your reply.

> Would it help your use-case to introduce specific matchers that make these id-to-id graphs more easy to access?

This would be great !

> Thanks again for sharing your use case and let me know if you'd be interested in collaborating on adding more support for id-to-id matchers in Nomer.

I will be happy to contribute to the best of my ability.

**Comment by jhpoelen** [comment]
@nleguillarme glad to hear your are willing to collaborate. I've started an integration to help extract wikidata taxon links (e.g., https://www.wikidata.org/wiki/Q53636 contains many links to other ids of 
Anura, an amphibians order). One thing I was wondering is how wikidata handles synonyms / unaccepted names (e.g., Arius felis is an unaccepted name of Ariopsis felis). Can you help figure that out?

**Comment by nleguillarme** [comment]
@jhpoelen it seems like there are two ways knowledge about synonyms is represented in wikidata :
https://www.wikidata.org/wiki/Wikidata:WikiProject_Taxonomy/Tutorial#Taxon_synonym

- via the 'taxon synonym' object property (P1420) if the synonym has an entry in wikidata
- via the 'skos:altLabel' data property if the synonym is a simple string

Here is a link to an example query using both methods : https://w.wiki/aKX

Is it what you were looking for ?

**Comment by jhpoelen** [comment]
Very cool, yes that is what I was looking for. 

Thanks for sharing the example to lookup reported synonyms for specific taxa (see copy below for ease of reading thread):

```
SELECT ?taxon (GROUP_CONCAT(DISTINCT(?synonym); separator = ", ") AS ?synonym_list) (GROUP_CONCAT(DISTINCT(?altLabel); separator = ", ") AS ?altLabel_list)
WHERE 
{
  BIND(wd:Q156301 AS ?taxon)
  OPTIONAL { ?taxon wdt:P1420 ?synonym .}
  OPTIONAL { ?taxon skos:altLabel ?altLabel .}
}
group by ?taxon`
```

In following the example, I do notice that the definition of taxon synonym ( https://www.wikidata.org/wiki/Property:P1420 ) is "(incorrect) name listed as synonym of a taxon name".  . 

In following the example:

A claim is made that:

Caprifoliaceae [Q156301](https://www.wikidata.org/wiki/Q156301) has (incorrect) synonym [P1420](https://www.wikidata.org/wiki/Property:P1420) Valerianaceae [Q156682](https://www.wikidata.org/wiki/Q156682). 

However, it appears that the inverse claim is also made:

Valerianaceae [Q156682](https://www.wikidata.org/wiki/Q156682).  has (incorrect) synonym [P1420](https://www.wikidata.org/wiki/Property:P1420) Caprifoliaceae [Q156301](https://www.wikidata.org/wiki/Q156301) 

So, it appears that wiki data claims contradict each other. 

@nleguillarme Just checking my understanding: Do you agree that a contradicting claim is made in above example?

**Comment by nleguillarme** [comment]
Yes you are right !
I also noticed that some synonyms (e.g. Morinaceae [Q133064](https://www.wikidata.org/wiki/Q133064), Linnaeaceae [Q134924](https://www.wikidata.org/wiki/Q134924)) are both instance of taxon [Q16521](https://www.wikidata.org/wiki/Q16521) and instance of 'synonym of Caprifoliaceae'

**Comment by jhpoelen** [comment]
@nleguillarme thanks for confirming. I guess any taxon id mapping scheme is expected to have mistakes, including the taxa synonym claims in wikidata. However, I wonder whether the claims we found are a difference in opinion (e.g., taxonomist A claims that X is a synonym of Y, taxonomist B claims that Y is a synonym of X), or the result of some faulty wikidata bot.  And this make me wonder: how does wikidata deal with conflicting expert opinion? Does the person with the biggest wikidata bot win? Or is there some way to capture and report disputes?  I noticed a discussion https://github.com/Wikidata/soweego/issues/220 in wikidata project by @marfox @fracorco and @Remper that may be relevant to annotating the confidence / quality of a certain claim. 

Regardless, I'd like to propose to start with supporting in Nomer for a id-to-id mapping via wikidata that does not include synonym resolution yet. We can always add this later. Are you ok with that? If y, what mapping scheme did you have in mind?

**Comment by jhpoelen** [comment]
perhaps @qgroom knows about conflict resolution / suspicious wikidata claims - I believe he went to some workshops with wikidata folks.

**Comment by jhpoelen** [comment]
Hey @nleguillarme - I just added a first pass of the wikidata id matcher to Nomer v0.1.15 . 

Now, you can use wikidata to map EOL ids to GBIF ids (or any other supported taxonomy). 

Example:
```
$ echo  "EOL:327955" | nomer append wikidata-taxon-id-web
using matcher [wikidata-taxon-id-web]
EOL:327955	SAME_AS	WD:Q15978631	Homo sapiens			Homo sapiens			https://www.wikidata.org/wiki/Q15978631	
EOL:327955	SAME_AS	NCBI:9606	Homo sapiens			Homo sapiens			https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606	
EOL:327955	SAME_AS	ITIS:180092	Homo sapiens			Homo sapiens			http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=180092	
EOL:327955	SAME_AS	EOL:327955	Homo sapiens			Homo sapiens			http://eol.org/pages/327955	
EOL:327955	SAME_AS	GBIF:2436436	Homo sapiens			Homo sapiens			http://www.gbif.org/species/2436436	
EOL:327955	SAME_AS	MSW:12100795	Homo sapiens			Homo sapiens				
EOL:327955	SAME_AS	INAT_TAXON:43584	Homo sapiens			Homo sapiens			https://inaturalist.org/taxa/43584	
EOL:327955	SAME_AS	NBN:NHMSYS0000376773	Homo sapiens			Homo sapiens			https://data.nbn.org.uk/Taxa/NHMSYS0000376773	
EOL:327955	SAME_AS	IRMNG:10857762	Homo sapiens			Homo sapiens			http://www.marine.csiro.au/mirrorsearch/ir_search.list_species?sp_id=10857762	
```

if you only want GBIF:

```
$ echo  "EOL:327955" | nomer append wikidata-taxon-id-web | grep GBIF
using matcher [wikidata-taxon-id-web]
EOL:327955	SAME_AS	GBIF:2436436	Homo sapiens			Homo sapiens			http://www.gbif.org/species/2436436	
```

Also, you can go the other way:

```
$ echo  "GBIF:2436436" | nomer append wikidata-taxon-id-web | grep EOL
using matcher [wikidata-taxon-id-web]
GBIF:2436436	SAME_AS	EOL:327955	Homo sapiens			Homo sapiens			http://eol.org/pages/327955	
```

@nleguillarme If this functionality help you with the EOL -> GBIF mapping, please close this issue. Otherwise, please suggest improvement / comments.  

PS Synonym resolution is not yet supported, but I'd be happy to add it if you have some need for it and would like to help. Also, the current version uses individual sparql queries using a remote service. For more performant service, a offline-enabled matcher can be built using a published archive like the one published in:

> Poelen, Jorrit. (2018). 20 GB in 10 minutes: Data linking across major biodiversity databases: Data supplements (Version 0.1) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.1213477 .

**Comment by jhpoelen** [comment]
fyi @jhammock @seltmann - Nomer now supports mapping EOL page ids to many taxonomies via wikidata.

**Comment by qgroom** [comment]
> perhaps @qgroom knows about conflict resolution / suspicious wikidata claims - I believe he went to some workshops with wikidata folks.

Wikidata is rather conflicted on biological taxonomy. It conflates scientific name and taxon data. There is no clear resolution to this, it is ultimately a problem with taxonomy that there is no single authority. It is effectively impossible to to create a list of taxa without choosing which authorities to follow.

**Comment by jhpoelen** [comment]
@qgroom thanks for sharing your take on wikidata. I can see how wikidata can provide a useful estimate for which taxa are related to each other (e.g., @nleguillarme 's use case of wanting to get the GBIF id for some EOL page id). And, when cross checking these taxon id relation estimates with other taxon graphs (e.g., Open Tree Taxonomy, EOL Dynamic Hierarchy, NCBI LinkOut) mapping inconsistencies can be detected and additional relations can be inferred (see @diatomsRcool 's paper https://doi.org/10.7717/peerj-cs.164 for some examples).
