### ISSUE TITLE
Looking for URI in NCBI but nomer append returns URI in EOL

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#29]
Hi @jhpoelen.

I have a taxon name "Achillea millefolium" and I want its URI in the NCBI Taxonomy.
Using nomer append globi-taxon-cache, here is the result

Achillea millefolium	SAME_AS	NCBI:13329	Achillea millefolium	species		| Eukaryota | Viridiplantae | Streptophyta | Streptophytina | Embryophyta | Tracheophyta | Euphyllophyta | Spermatophyta | Magnoliophyta | Mesangiospermae |  | Gunneridae | Pentapetalae |  |  | Asterales | Asteraceae | Asteroideae | Anthemideae | Matricariinae | Achillea | Achillea millefolium complex | Achillea millefolium	NCBI:131567 | NCBI:2759 | NCBI:33090 | NCBI:35493 | NCBI:131221 | NCBI:3193 | NCBI:58023 | NCBI:78536 | NCBI:58024 | NCBI:3398 | NCBI:1437183 | NCBI:71240 | NCBI:91827 | NCBI:1437201 | NCBI:71274 | NCBI:91882 | NCBI:4209 | NCBI:4210 | NCBI:102804 | NCBI:102810 | NCBI:886729 | NCBI:13328 | NCBI:1095267 | NCBI:13329	|  | kingdom | phylum | subphylum |  |  |  |  |  |  |  |  |  | subclass |  | order | family | subfamily | tribe | subtribe | genus |  | species	http://eol.org/pages/467225

As you can see, the URI is http://eol.org/pages/467225, instead of https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=13329.

(A possible workaround is to use a map linking prefixes to URI.)

**Comment by jhpoelen** [comment]
@nleguillarme thanks for sharing. 

The EOL urls were leftover from older versions of the GloBI Taxon Graph. 

I just now released Nomer v0.1.22 . This version point to v0.3.28 of the GloBI Taxon Graph. This version includes some NCBI sanitizing. 

Now, the match:

```shell
$ echo -e "\tAchillea millefolium" | nomer append | grep NCBI
	Achillea millefolium	SAME_AS	NCBI:13329	Achillea millefolium	species		root | cellular organisms | Eukaryota | Viridiplantae | Streptophyta | Streptophytina | Embryophyta | Tracheophyta | Euphyllophyta | Spermatophyta | Magnoliopsida | Mesangiospermae | eudicotyledons | Gunneridae | Pentapetalae | asterids | campanulids | Asterales | Asteraceae | Asteroideae | Anthemideae | Matricariinae | Achillea | Achillea millefolium complex | Achillea millefolium	NCBI:1 | NCBI:131567 | NCBI:2759 | NCBI:33090 | NCBI:35493 | NCBI:131221 | NCBI:3193 | NCBI:58023 | NCBI:78536 | NCBI:58024 | NCBI:3398 | NCBI:1437183 | NCBI:71240 | NCBI:91827 | NCBI:1437201 | NCBI:71274 | NCBI:91882 | NCBI:4209 | NCBI:4210 | NCBI:102804 | NCBI:102810 | NCBI:886729 | NCBI:13328 | NCBI:1095267 | NCBI:13329	|  | superkingdom | kingdom | phylum | subphylum | clade | clade | clade | clade | class | clade | clade | clade | clade | clade | clade | order | family | subfamily | tribe | subtribe | genus |  | species	https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=13329	
	Achillea millefolium	SAME_AS	NCBI:13328	Achillea	genus		root | cellular organisms | Eukaryota | Viridiplantae | Streptophyta | Streptophytina | Embryophyta | Tracheophyta | Euphyllophyta | Spermatophyta | Magnoliopsida | Mesangiospermae | eudicotyledons | Gunneridae | Pentapetalae | asterids | campanulids | Asterales | Asteraceae | Asteroideae | Anthemideae | Matricariinae | Achillea	NCBI:1 | NCBI:131567 | NCBI:2759 | NCBI:33090 | NCBI:35493 | NCBI:131221 | NCBI:3193 | NCBI:58023 | NCBI:78536 | NCBI:58024 | NCBI:3398 | NCBI:1437183 | NCBI:71240 | NCBI:91827 | NCBI:1437201 | NCBI:71274 | NCBI:91882 | NCBI:4209 | NCBI:4210 | NCBI:102804 | NCBI:102810 | NCBI:886729 | NCBI:13328	|  | superkingdom | kingdom | phylum | subphylum | clade | clade | clade | clade | class | clade | clade | clade | clade | clade | clade | order | family | subfamily | tribe | subtribe | genus	https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=13328	
```

notice that the urls are now pointing to the ncbi endpoints. Please do note that the urls are, and can be, generated from the NCBI taxon ids. 

Please re-open this issue if you feel more is needed to address your needs.
