### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#3]
from @marieALaporte

 I am having an hard time building nomer.
This is the error I am getting. I am probably not doing something as I should…. Should I use the version I have ?

 Failed to execute goal on project nomer-taxon-resolver: Could not resolve dependencies for project org.globalbioticinteractions:nomer-taxon-resolver:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [org.eol:eol-globi-taxon-resolver:jar:0.9.11 (compile), junit:junit:jar:4.12 (test), org.mockito:mockito-all:jar:1.9.0 (test)]: Failed to read artifact descriptor for org.eol:eol-globi-taxon-resolver:jar:0.9.11: Could not transfer artifact org.eol:eol-globi-taxon-resolver:pom:0.9.11 from/to globi-release-http (https://depot.globalbioticinteractions.org/release): peer not authenticated -> [Help 1]

**Comment by jhpoelen** [comment]
I was unable to reproduce this issue using:

```
$ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-112-generic", arch: "amd64", family: "unix"
```

@mariealaporte - which java / mvn version are you using?

**Comment by marieALaporte** [comment]
Apache Maven 3.5.2 fixed the issue. Thanks
