### ISSUE TITLE
add support for using [path.kingdom.name] as column type in output schema

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#35]
add ability to use output schema as suggested by @zedomel 

```
this nomer.schema.output=[{"column": 0,"type":"path.kingdom.name"}] should give me kingdom's names with nomer replace
```

https://github.com/globalbioticinteractions/nomer/blob/9214b02abd2d84fbaf570f877baf911dbe9d54a2/nomer/src/main/java/org/globalbioticinteractions/nomer/util/ReplacingRowHandler.java#L59

**Comment by zedomel** [comment]
@jhpoelen 

I tried to use 
```
nomer.schema.input=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"},{"column":2,"type":"path.kingdom.name"}]
nomer.schema.output=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"},{"column":2, "type":"path.kingdom.name"}]
```

But seems that `nomer` does not understand the `type: "path.kingdom.name"`. Where should it be handle? May be in the same way of: [https://github.com/globalbioticinteractions/nomer/blob/8d4e2d70d0023f04bd33d2ad087fe4921050630a/nomer/src/main/java/org/globalbioticinteractions/nomer/util/AppenderTSV.java#L60](https://github.com/globalbioticinteractions/nomer/blob/8d4e2d70d0023f04bd33d2ad087fe4921050630a/nomer/src/main/java/org/globalbioticinteractions/nomer/util/AppenderTSV.java#L60) ?

What are you thinking?

**Comment by jhpoelen** [comment]
@zedomel yes, Nomer needs to get a little smarter in interpreting the column types in context of a specific taxonomic path. 

As far as I understand, we'd like to have something like:

```
$ echo -e "\tHomo sapiens" | nomer replace -p [... some property magic ...]
NCBI:9606{tab}Homo sapiens{tab}Animalia
```
 
where the third column type is the ```path.kingdom.name```, and the first and second are taxon id and taxon name.

@zedomel does that capture our expected outcome after adding this new feature?

**Comment by zedomel** [comment]
yea! sound's perfect.

**Comment by jhpoelen** [comment]
Note that while trying to figure out how to implement this, the Nomer's json support might be helpful - 

```
$ echo -e "\tHomo sapiens" | nomer append -o json globi-globalnames | jq .kingdom
using matcher [globi-globalnames]
{
  "@id": "NCBITaxon:33208",
  "name": "Metazoa"
}
{
  "@id": "OTT:691846",
  "name": "Metazoa"
}
{
  "@id": "ITIS:202423",
  "name": "Animalia"
}
{
  "@id": "IRMNG:11",
  "name": "Animalia"
}
{
  "@id": "WORMS:2",
  "name": "Animalia"
}
{
  "@id": "GBIF:1",
  "name": "Animalia"
}
```

similar results should be possible using the ```ncbi-taxa``` matcher.

**Comment by jhpoelen** [comment]
@zedomel with recent changes, the following results are produced:

```
$ echo -e "\tHomo sapiens\t" | nomer replace -p nomer.properties globi-globalnames
	Homo sapiens	Metazoa
```

where nomer.properties contains:

```
nomer.schema.output=[{"column":2,"type":"path.kingdom.name"}]
```

Similarly, a value can be overridden, by

```
$ echo -e "\tHomo sapiens\t" | nomer replace -p nomer.properties globi-globalnames
	Metazoa	
```

where nomer.properties contains:

```
nomer.schema.output=[{"column":1,"type":"path.kingdom.name"}]
```

the ```ncbi-taxa``` matcher should produce similar results when used instead of the ```globi-globalnames``` matcher.

This functionality will be included in next Nomer release (i.e., v0.1.27)

**Comment by jhpoelen** [comment]
@zedomel just released https://github.com/globalbioticinteractions/nomer/releases/tag/0.1.27 please let me know if this version has the desired functionality by commenting or reopening this issue.
