### ISSUE TITLE
failing OpenBiodiv regression tests 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#36]
For some reason, some assertions in two regression tests of Nomer against OpenBiodiv no longer hold:

1. 4B689A17-2541-4F5F-A896-6F0C2EEA3FB4 still has name Acanthaceae , but is no longer reported to be a ```family```. Instead, the rank is reported to be a ```genus```. 

https://github.com/globalbioticinteractions/nomer/blob/b632a19e0bfb5adb8c7aaf84f3eaa667571d008e/nomer-taxon-resolver/src/test/java/org/globalbioticinteractions/nomer/util/OpenBiodivUtilTest.java#L26-L31

2. 22A7F215-829B-458A-AEBB-39FFEA6D4A91 still has name _Bolacothrips striatopennatus_ , but the rank is no longer ```species```. Instead, a ```null``` value is reported (no rank information). 

https://github.com/globalbioticinteractions/nomer/blob/b632a19e0bfb5adb8c7aaf84f3eaa667571d008e/nomer-taxon-resolver/src/test/java/org/globalbioticinteractions/nomer/util/OpenBiodivUtilTest.java#L53-L57

@mdmtrv please let me know if you can help provide insights on why the assertions related to the examples above (see also linked tests code) no longer hold.

**Comment by mdmtrv** [comment]
Hi Jorrit,

I took a quick look and it seems like both taxonomic name usages come from the same taxonomic key in the paper [https://doi.org/10.3897/zookeys.306.5455](https://doi.org/10.3897/zookeys.306.5455). Taxonomic keys are in table format which might be what messed up the information extraction. Nevertheless, I have no idea where the genus rank came from in the first assertion. I would look into it tomorrow and would probably reprocess this particular paper to figure out why these ranks are messed up. Regarding the second example, the taxonomic key actually does not mention the rank of _Bolacothrips striatopennatus_.

**Comment by jhpoelen** [comment]
@mdmtrv Just revisited this "ancient" issue (e.g., June 2021) related to openbiodiv regression tests. 

After re-enabling the OpenBiodiv tests, the tests assertions held up, except for the taxonomic rank of 22A7F215-829B-458A-AEBB-39FFEA6D4A91 / _Bolacothrips striatopennatus_ . And your careful note:

> Regarding the second example, the taxonomic key actually does not mention the rank of Bolacothrips striatopennatus.

Helped me understand that the taxonomic key does not actually mention the rank of the name. 

Thanks again for your attention to detail.
