### ISSUE TITLE
Add DiscoverLife Bees to Nomer

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#42]
@jhpoelen Can we add the Discover Life bee checklist to Nomer?
https://www.discoverlife.org/mp/20q?act=x_checklist&guide=Apoidea_species&flags=HAS:

Ascher, J. S. and J. Pickering. 2020.
Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila).
http://www.discoverlife.org/mp/20q?guide=Apoidea_species

**Comment by jhpoelen** [comment]
A quick performance test shows that the (un-optimized) Discover Life taxon matcher can match about 3k names/s or 3 names / ms.

**Comment by seltmann** [comment]
@jhpoelen 20K names is right. That is about the number of worldwide bee species.

  Acamptopoeum vagans (Cockerell, 1926) -- Camptopoeum (Acamptopoeum) vagans Cockerell, 1926
  
  Current valid name - Acamptopoeum vagans (Cockerell, 1926)
  Scientific Name -  Acamptopoeum vagans
  Aurhorship - (Cockerell, 1926)
  Other name - Camptopoeum (Acamptopoeum) vagans Cockerell, 1926
  
  Other names are not defined by Discover Life except on a few occasions, but most are prior names for the current valid taxon

**Comment by seltmann** [comment]
Andrena accepta Viereck, 1916 -- Andrena pulchella_homonym Robertson, 1891; Pterandrena pulchella (Robertson, 1891); Andrena accepta Viereck, 1916, replacement name
  
  Current valid name - Andrena accepta Viereck, 1916
  Scientific Name -  Andrena accepta
  Aurhorship - Viereck, 1916
  Other names - Andrena pulchella Robertson, 1891; Pterandrena pulchella (Robertson, 1891); Andrena accepta Viereck, 1916
  
  Andrena pulchella_homonym Robertson, 1891 - indicates that  Andrena pulchella is a homonym
  Andrena accepta Viereck, 1916 - not entirely sure what replacement name indicates, but some kind of synonym

**Comment by jhpoelen** [comment]
@seltmann thanks for providing your manually parsed examples. 

here's the markup associated to the examples:

```html
<td>
&nbsp;&nbsp;&nbsp;
<i><a href="/mp/20q?search=Acamptopoeum+vagans" target="_self">Acamptopoeum vagans</a></i> 
<font size="-1" face="sans-serif">(Cockerell, 1926)</font> 
-- 
<i>Camptopoeum (Acamptopoeum) vagans </i>Cockerell, 1926
</td>
```

and 

```html
<td>&nbsp;&nbsp;&nbsp;
<i><a href="/mp/20q?search=Andrena+accepta" target="_self">Andrena accepta</a></i> 
<font size="-1" face="sans-serif">Viereck, 1916</font> 
-- 
<i>Andrena pulchella_homonym </i>Robertson, 1891; 
<i>Pterandrena pulchella </i>(Robertson, 1891); 
<i>Andrena accepta </i>Viereck, 1916, replacement name
</td>
```

**Comment by seltmann** [comment]
Example with subgenus

  Andrena anisochlora Cockerell, 1936 -- Andrena (Micrandrena) dinognatha Timberlake, 1938
Current valid name - Andrena anisochlora Cockerell, 1936
Scientific Name - Andrena anisochlora
Authorship - Cockerell, 1936
Other names - Andrena (Micrandrena) dinognatha Timberlake, 1938

Where (Micrandrena) is a subgenus which is always in paranthesis after the genus

**Comment by jhpoelen** [comment]
@seltmann closing main issue of adding discoverlife support. Please report specific issues/ improvement suggestions in separate issues.
