### ISSUE TITLE
NONE in discoverlife names for name type

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#53]
In a few names in the name type field (i.e. HAS_ACCEPTED_NAME, SYNONYM_OF) NONE appears. For example:

https://www.discoverlife.org/mp/20q?search=Allodape+clypeata	Allodape clypeata	NONE	https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	Allodape obscuripennis	species		Animalia | Arthropoda | Insecta | Hymenoptera | Apidae | Allodape obscuripennis	https://www.discoverlife.org/mp/20q?search=Animalia | https://www.discoverlife.org/mp/20q?search=Arthropoda | https://www.discoverlife.org/mp/20q?search=Insecta | https://www.discoverlife.org/mp/20q?search=Hymenoptera | https://www.discoverlife.org/mp/20q?search=Apidae | https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	kingdom | phylum | class | order | family | species	https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis

**Comment by jhpoelen** [comment]
Thanks for sharing your observation about the reported NONE name relations. 

From the first example, _Allodape clypeata_ , I make the attached screenshots from https://www.discoverlife.org/mp/20q?search=Allodape+clypeata . 

Note that the page resolves to:
 Allodape obscuripennis Strand, 1915
with related names:
 * Allodape clypeata Strand, 1915
 * Allodape clypeata_homonym Friese, 1924

So, at first glance, discoverlife notes that Allodape clypeata Strand, 1915 has homonym Allodape clypeata Friese, 1924 . 

![Screenshot from 2021-11-01 14-56-52](https://user-images.githubusercontent.com/1084872/139747538-9a95571e-803e-4487-af9c-45e28bd4752a.png)

@seltmann how would you like to have this homonym relationship between Allodape clypeata_homonym and their counter parts be represented in the nomer output?

**Comment by seltmann** [comment]
@jhpoelen please add HAS_HOMONYM or HOMONYM_OF relationship when explicit **_homonym**

**Comment by jhpoelen** [comment]
I added HOMONYM_OF name relationship, see attached output of 

```
$ nomer list discoverlife | gzip > discoverlife.tsv.gz 
```

note that 

```
$ zcat discoverlife.tsv.gz | grep "HOMONYM" | wc -l
874
```

and
 
```
$ zcat discoverlife.tsv.gz | grep "HOMONYM" | grep "no:match" | wc -l
517
```

with 

```
$ zcat discoverlife.tsv.gz | grep "HOMONYM" | grep "no:match" | head -n2
https://www.discoverlife.org/mp/20q?search=Allodape+longula	Allodape longula	HOMONYM_OF	no:match	no:match							
https://www.discoverlife.org/mp/20q?search=Amegilla+bicincta	Amegilla bicincta	HOMONYM_OF	no:match	no:match														
```

suggesting that the majority of homonyms found do not have an another (accepted) homonym mentioned in the same corpus. Is this expected?

**Comment by jhpoelen** [comment]
Also, for some positive examples:

```
$ zcat discoverlife.tsv.gz | grep "HOMONYM" | grep -v "no:match" | head -n2
https://www.discoverlife.org/mp/20q?search=Allodape+friesei	Allodape friesei	HOMONYM_OF	https://www.discoverlife.org/mp/20q?search=Allodape+friesei	Allodape friesei	species		Animalia | Arthropoda | Insecta | Hymenoptera | Apidae | Allodape friesei	https://www.discoverlife.org/mp/20q?search=Animalia | https://www.discoverlife.org/mp/20q?search=Arthropoda | https://www.discoverlife.org/mp/20q?search=Insecta | https://www.discoverlife.org/mp/20q?search=Hymenoptera | https://www.discoverlife.org/mp/20q?search=Apidae | https://www.discoverlife.org/mp/20q?search=Allodape+friesei	kingdom | phylum | class | order | family | species	https://www.discoverlife.org/mp/20q?search=Allodape+friesei	
https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	Allodape obscuripennis	HOMONYM_OF	https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	Allodape obscuripennis	species		Animalia | Arthropoda | Insecta | Hymenoptera | Apidae | Allodape obscuripennis	https://www.discoverlife.org/mp/20q?search=Animalia | https://www.discoverlife.org/mp/20q?search=Arthropoda | https://www.discoverlife.org/mp/20q?search=Insecta | https://www.discoverlife.org/mp/20q?search=Hymenoptera | https://www.discoverlife.org/mp/20q?search=Apidae | https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	kingdom | phylum | class | order | family | species	https://www.discoverlife.org/mp/20q?search=Allodape+obscuripennis	
```

**Comment by jhpoelen** [comment]
Also, please note that the NONE relationship no longer occur:

```
$ nomer list discoverlife | grep "NONE" | wc -l
using matcher [discoverlife-taxon]
0
```
