### ISSUE TITLE
unexpected _homonym suffixes in [nomer list discoverlife]

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#63]
as reported by @seltmann in https://github.com/globalbioticinteractions/nomer/issues/58#issuecomment-968056591 . 

See complete list (63 in total) of attached _homonym matches from the

 ```
$ nomer list discoverlife | grep _homonym | gzip > unexpected_homonyms.tsv.gz
```

[unexpected_homonyms.tsv.gz](https://github.com/globalbioticinteractions/nomer/files/7541721/unexpected_homonyms.tsv.gz)

**Comment by jhpoelen** [comment]
Note that this affects 63 out of ```nomer list discoverlife | wc -l``` 50621 name relations.

**Comment by jhpoelen** [comment]
@seltmann when discoverlife says:

<tr bgcolor=\"#f0f0f0\">\n" +
                "            <td>\n" +
                "                 \n" +
                "              <i>\n" +
                "                <a href=\"/mp/20q?search=Anthidiellum+boreale_homonym\" target=\"_self\">\n" +
                "                  Anthidiellum boreale_homonym\n" +
                "                </a>\n" +
                "              </i>\n" +
                "              <font size=\"-1\" face=\"sans-serif\">\n" +
                "                Wu, 2004\n" +
                "              </font>\n" +
                "               -- \n" +
                "              <i>\n" +
                "                Anthidiellum (Anthidiellum) borealis_homonym \n" +
                "              </i>\n" +
                "              Wu, 2004\n" +
                "            </td>\n" +
                "          </tr>\n

How would you translate this into the name relations?

Would it look like:
```
Anthidiellum boreale | has accepted name | Anthidiellum boreale
Anthidiellum boreale | homonym of | ...
Anthidiellum (Anthidiellum) borealis | synonym of | Anthidiellum boreale
Anthidiellum (Anthidiellum) borealis | homonym of | ...
```
?

**Comment by seltmann** [comment]
@jhpoelen wow, I am not sure.

Since they are both homonyms, neither are valid and it looks like they are homonyms of each other.

Anthidiellum boreale homonym of Anthidiellum (Anthidiellum) borealis

Anthidiellum (Anthidiellum) borealis homonym of Anthidiellum boreale

**Comment by jhpoelen** [comment]
Ok, so if two names with _homonym suffixes are related, and they have the same name (not authorship), then they are homonyms of each other.

**Comment by jhpoelen** [comment]
And they are not accepted names.

**Comment by jhpoelen** [comment]
Nor are they synonyms.

**Comment by jhpoelen** [comment]
@seltmann I'd like to better understand you interpretation of this discoverlife homonym business. 

> @jhpoelen wow, I am not sure.

I'd rather spend a little more time on these remaining issues (63 out of about 50k names), than make some fix that we'll end up changing afterwards.

**Comment by seltmann** [comment]
@jhpoelen you are correct. They should only be considered homonyms, not synonyms or accepted names.

**Comment by jhpoelen** [comment]
@seltmann thanks for clarifying. I am assuming that the discoverlife folks added to homonym to say something like: do not use this name, because it is a homonym. 

Why not simply ignore all homonyms?

**Comment by jhpoelen** [comment]
@seltmann I did some more work on these discoverlife homonyms and found that my interpretation (e.g., homonyms cannot be accepted names) does not match with the redirect of

https://www.discoverlife.org/mp/20q?search=Proteriades+similis

to 

the Hoplitis similis_homonym page. 

Please advise on the interpretation of this redirect and included page.

See attached screenshot.

![Screenshot from 2021-11-23 14-48-12](https://user-images.githubusercontent.com/1084872/143141205-ca3bce26-28e6-4ed7-a50c-aabcf582a766.png)

**Comment by jhpoelen** [comment]
@seltmann Another pass at appropriate homonym handling can be found in Nomer v0.2.9 . Please review.
