### ISSUE TITLE
list supported schema terms 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#67]
@seltmann  suggested to:

> can I get a list of other properties I can add to my.properties? I see that nomer -p allows me to use a custom properties, but can I configure this to also include resolvedPath for example. Thanks!

mentioned in issue #54 .

**Comment by jhpoelen** [comment]
for now, you can copy-paste from the default appender output schema:

```
$ nomer properties | grep append.schema.output | cut -d '=' -f2 | jq .
[
  {
    "column": 0,
    "type": "externalId"
  },
  {
    "column": 1,
    "type": "name"
  },
  {
    "column": 2,
    "type": "rank"
  },
  {
    "column": 3,
    "type": "commonNames"
  },
  {
    "column": 4,
    "type": "path"
  },
  {
    "column": 5,
    "type": "pathIds"
  },
  {
    "column": 6,
    "type": "pathNames"
  },
  {
    "column": 7,
    "type": "externalUrl"
  },
  {
    "column": 8,
    "type": "thumbnailUrl"
  }
]
```

so, to include resolvedPath, add ```path``` as some numbered column type in your schema.

**Comment by seltmann** [comment]
@jhpoelen perfect. I was able to modify my.properties to include type:path for inclusion of the family name into the file.
