### ISSUE TITLE
No result in IndexFungorum using wikidata-web

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#71]
Hi @jhpoelen 

Looking for taxid IF:7106 using wikidata-web gets me no result.
Looking for the same taxon using its NCBI id NCBI:128151 gets me some results, but none in the IndexFungorum taxo, although the info is in wikidata : https://www.wikidata.org/wiki/Q133266

Does the wikidata-web matcher apply some filter to discard results in "unwanted" taxonomies ?

**Comment by jhpoelen** [comment]
Hey @nleguillarme thanks for sharing that you expected:

```
$ echo -e "IF:7106" | nomer wikidata-web 
```

to resolve some fungus taxon known to index fungorum , but instead got something like:

```
IF:7106	NONE	IF:7106							http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=7106
```
as a result. 

I checked the implementation and found that the WikiData's support for the Index Fungorum taxon identification scheme was not yet known (i.e. mapped) to Nomer.

I've added the mapping and extra tests. The functionality should be available in the next Nomer release. 

Please let me know if this is urgent, or whether you are ok waiting a couple of weeks. 

-jorrit  

 about the missing mapping between index fungorum and their associated Wikidata property id.

**Comment by jhpoelen** [comment]
Note that the upcoming Nomer version is producing results like:

```
$ echo -e "IF:7106" | nomer append wikidata-web 
IF:7106	SAME_AS	WD:Q133266	Alternaria			Alternaria	https://www.wikidata.org/wiki/Q133266	
IF:7106	SAME_AS	NCBI:5598	Alternaria			Alternaria	https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=5598	
IF:7106	SAME_AS	ITIS:14134	Alternaria			Alternaria	http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=14134	
IF:7106	SAME_AS	EOL:16498	Alternaria			Alternaria	http://eol.org/pages/16498	
IF:7106	SAME_AS	GBIF:2616104	Alternaria			Alternaria	http://www.gbif.org/species/2616104	
IF:7106	SAME_AS	WORMS:100208	Alternaria			Alternaria	https://www.marinespecies.org/aphia.php?p=taxdetails&id=100208	
IF:7106	SAME_AS	IF:7106	Alternaria			Alternaria		http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=7106	
IF:7106	SAME_AS	INAT_TAXON:327996	Alternaria			Alternaria			https://inaturalist.org/taxa/327996	
IF:7106	SAME_AS	NBN:NHMSYS0001474393	Alternaria			Alternaria			https://data.nbn.org.uk/Taxa/NHMSYS0001474393	
IF:7106	SAME_AS	IRMNG:1312559	Alternaria			Alternaria	https://www.irmng.org/aphia.php?p=taxdetails&id=1312559	
IF:7106	SAME_AS	OTT:464790	Alternaria			Alternaria	https://tree.opentreeoflife.org/opentree/ottol@464790	
```

Please let me know the above result is as expected.

**Comment by nleguillarme** [comment]
Hi @jhpoelen , that's it, thank you !
Fast as lightning as always. This can wait a few weeks until you're ready to release a new version.

**Comment by jhpoelen** [comment]
@nleguillarme happy to help and thanks for confirming. Also, I am able to work quickly because of the immense amount of work our open source/data colleagues have already done/do around the world.
