### ISSUE TITLE
Duplicate rows as seen by https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/53

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#72]
While working on indexing the Discoverlife data, duplicate rows were observed per [this issue ](https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/53).

**Comment by jhpoelen** [comment]
@seltmann In the upcoming Nomer release, an attempt is made to no longer list self-referential synonym name relations. 

In previous version, a self-referential synonym of Pseudapis neumayeri was generated via ```nomer ls discoverlife```.

Now, only the accepted name relation is provided:

```
$ nomer ls discoverlife | grep "Pseudapis neumayeri"
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [discoverlife-taxon]
https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri	Pseudapis neumayeri	HAS_ACCEPTED_NAME	https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri	Pseudapis neumayeri	species		Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri	https://www.discoverlife.org/mp/20q?search=Animalia | https://www.discoverlife.org/mp/20q?search=Arthropoda | https://www.discoverlife.org/mp/20q?search=Insecta | https://www.discoverlife.org/mp/20q?search=Hymenoptera | https://www.discoverlife.org/mp/20q?search=Halictidae | https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri	kingdom | phylum | class | order | family | species	https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri	
```

**Comment by jhpoelen** [comment]
@seltmann thanks for checking my work. Glad to hear that @dimus was able to index the DiscoverLife bee checklist now https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/53 .

from https://resolver.globalnames.org/ searching by _Apis mellifera_ - 

![Screenshot from 2022-02-22 11-38-53](https://user-images.githubusercontent.com/1084872/155187639-bfdde968-89df-4fbc-bcbb-fdd4cca6decc.png)
