### ISSUE TITLE
Add citation for EOL Dynamic Hierarchy

### ISSUE THREAD

**Issue by KatjaSchulz** [globalbioticinteractions/nomer#75]
Encyclopedia of Life. 2022. Encyclopedia of Life Dynamic Hierarchy Data Sets. Available from https://opendata.eol.org/organization/about/dynamic-hierarchy

**Comment by jhpoelen** [comment]
Also includes wikidata and catalogue of life. 

fyi @Daniel-Mietchen

**Comment by jhammock** [comment]
our latest attempt at cross mapping: https://opendata.eol.org/dataset/identifier-map

**Comment by jhpoelen** [comment]
see #139
